config/routes.rb
Rails.application.routes.draw do
    # GET /about goes to about controller with index action
    get "about", to:"about#index"
    
    get "password", to: "passwords#edit", as: :edit_password
    patch "password", to: "passwords#update"

    # when people go to the sign_up url, it will take them to the registrations controller with the action being new
    get "sign_up", to: "registrations#new"
    post "sign_up", to: "registrations#create"

    get "sign_in", to: "sessions#new"
    post "sign_in", to: "sessions#create"

    delete "logout", to: "sessions#destroy"

    get "password/reset", to: "password_resets#new"
    post "password/reset", to: "password_resets#create"

    get "password/reset/edit", to: "password_resets#edit"
    patch "password/reset/edit", to: "password_resets#update"


    # get "/", to: "main#index" # This does the same thing as below
    root to: "main#index"

    # user registration
    get "sign_up", to: "registrations#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord # Inheriting from ApplicationRecord class so we get those methods. This itself is a subclass of ActiveRecord::Base which is the ORM for Ruby
    # Below will use the password_digest column in the database and it's going to add a password and confirmation to our user. Thes are virutal attributes that don't get saved to the database. When users submit a password it will be encrypted with bcrypt then saved in the database
    has_secure_password 
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Please enter a valid email address"} # Basically the same as required
    
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    # Inherit from controller
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # This is where all of our controllers inherit from, so these methods are basically global
    before_action :set_current_user # This will be the first thing that happens when you make a request with the Rails app i.e. whenever you try to do any action

    def set_current_user
        if session[:user_id] # If there is user_id in the session object cookie
            Current.user = User.find_by(id: session[:user_id]) # Returns us the number for the user. find_by is like find but does not throw an error if the user gets deleted mid session. Session is created and managed by ActionDispatch::Session middleware which is included by default in Rails apps and is configured in config/application.rb
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that" if Current.user.nil?
    end


end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        # if session[:user_id] # If there is user_id in the session object cookie
        #     @user = User.find_by(id: session[:user_id]) # Returns us the number for the user. find_by is like find but does not throw an error if the user gets deleted mid session. Session is created and managed by ActionDispatch::Session middleware which is included by default in Rails apps and is configured in config/application.rb
        # # flash.now[:notice] = "Logged in successfully"
        # # flash.now[:alert] = "Invalid email or password"
        # end
        
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new 
    end

    def create 
        @user = User.find_by(email: params[:email])

        if @user.present?
            
            # TODO Send email
            # Go to password mailer, semd the reset email with (using) parameters of user, and deliver later so it's done in background
            PasswordMailer.with(user: @user).reset.deliver_now
        else
        end

        redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password"

    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in! # This keeps the below stuff from happening if the user is not logged in. It's defined in application_controller.rb

    def edit 
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated!"
        else 
            # redirect_to edit_password_path
            render :edit
        end

    end
    
    private 

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController 
    def new
        # The @ symbol below makes user into an instance variable instead of a normal local variable, so it will have global scope within the view
        @user = User.new
    end

    def create
        # params is the data output from the form and URL
        # params is a method defined in the controller class that all controllers inherit from, so we're inheriting params method from parent
        @user = User.new(user_params) # Creating a new user via the User class and passing in user_params as the arguments for the new user constructor
        if @user.save # Returns true if user was successfully saved to database
            session[:user_id] = @user.id # Here we are creating the user_id key and value in the session object
            redirect_to root_path, notice: "Successfully created account!"
        else
            render :new # If something went wrong just re-render the new page in views/registrations/new.html.erb
        end

    end

    private # private is keyword meaning all subsequent (below) methods are private

    def user_params 
        params.require(:user).permit(:email, :password, :password_confirmation) # require requires that the user key exists and throws an error otherwise. permit returns a new hash that contains only the specified key/values
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create 
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully!"
        else
            flash[:alert] = "Invalid email or password"
            # render :new # Must redirect instead now in Rails
            redirect_to sign_in_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%# Below we are going to render a separate view to use as a navbar, kind of like a React component %>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= render partial: "shared/flash"%>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<%# Need to run from Ubuntu WSL. Start development server with "rails server" or "rails scd" %>
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to scheduled tweets</h1>
</div>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with  url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "username@email.com" %>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%=flash.now[:notice]%>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%=flash.now[:alert]%>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary " %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>